repository:
  name: SKENAI
  description: The Infinite Game - AI Blockchain Platform
  homepage: https://shibakenfinance.github.io/SKENAI
  topics: blockchain, ai, ethereum, smart-contracts
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "Documentation"
          - "test"
          - "lint"
      enforce_admins: false
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "test"
          - "lint"
      enforce_admins: false
      restrictions: null

labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"

  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"

  - name: "documentation"
    color: "0075ca"
    description: "Documentation improvements"

  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"

  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

  - name: "priority: high"
    color: "d93f0b"
    description: "High priority task"

  - name: "priority: medium"
    color: "fbca04"
    description: "Medium priority task"

  - name: "priority: low"
    color: "0e8a16"
    description: "Low priority task"

  - name: "security"
    color: "ee0701"
    description: "Security related issue"

  - name: "technical debt"
    color: "ff7619"
    description: "Technical improvements needed"
