theme: jekyll-theme-minimal
title: SKENAI Documentation
description: The Infinite Game - AI Blockchain Documentation
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
